### PR TITLE
Migrated benchmarks to criterion

### PR DESCRIPTION
**Pull request by AlexMikhalev**
Fancy plots and no need for unstable rust. 
Next step port benchmarks, any ideas?

### CODE REVIEW

**Comment by prataprc** [comment]
Thanks for the benchmark, moving away from unstable is a good idea. Though criterion is a bit overkill for our benchmarks, I am interested in this patch.

Ran this patch and got some fancy results (with graph et al..) One crib though - is it possible to avoid generating the report under xorfilter/target directory ? Looks like criterion is not respecting ~/.cargo/config[target_dir] option, not sure.

**Comment by AlexMikhalev** [comment]
@prataprc Criterion seems to be fairly popular for data structure benchmarking, I am currently looking at [pdatastructures](https://github.com/crepererum/pdatastructs.rs) to make a common benchmark of probabilistic data structures.

**Comment by AlexMikhalev** [comment]
I found a commit for change of target directory for criterion reports in [cargo-criterion](https://github.com/bheisler/cargo-criterion/commit/722b5acb3cc23272d60fb68e9d9fc0321e1da2a2), seems doable but adds one more dependency. Personally, I would make the cargo criterion part of my workspace.

**Comment by prataprc** [comment]
Found 2 issues related to configurable target-dir.

https://github.com/bheisler/criterion.rs/pull/337
https://github.com/bheisler/criterion.rs/issues/381

Looks like _author_ is taking the cargo-criterion as the recommended path for using criterion.

**Comment by prataprc** [comment]
When running with cargo-criterion, hit this issue.

```
Gnuplot not found, using plotters backend                                                                                                    
populate_keys_100000    time:   [4.1320 ms 4.1508 ms 4.1710 ms]                                                                                                                               
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', /home/prataprc/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.0.0/src/st
ats/univariate/sample.rs:29:9  
```

**Comment by AlexMikhalev** [comment]
@prataprc same seems issue [17](https://github.com/bheisler/cargo-criterion/issues/17) in their repo. I only was interested in criterion benchmarks.

**Comment by prataprc** [comment]
Let us hope criterion will become main-stream.

a. For now, let us allow criterion to create target/ under <repo-root>.
b. Ignore target/ dir in .gitignore.
c. Open a new issue to track criterion TARGET_DIR configuration.

**Comment by prataprc** [comment]
Thanks for the PR.

**Comment by AlexMikhalev** [comment]
@prataprc thank you, you also merged a tiny change in lib.rs line 444 as suggested by cargo clippy.

**Pull request merged**
