### PR TITLE
Refactor: correct method names: xx_keys should be xx_digests

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Refactor: correct method names: xx_keys should be xx_digests

This is a **breaking** change: public method names changed.

### Compatibility concern

Is it OK to just rename them?
Would it be necessary to keep the old name methods for compatibility?

- Improvement

### CODE REVIEW

**Comment by prataprc** [comment]
We have already merged a breaking change. I will review this before making the release. Meanwhile, is there a way to document via `attributes` to indicate the reason/remedies for a breaking API change ? I searched, couldn't spot

**Comment by drmingdrmer** [comment]
> We have already merged a breaking change. I will review this before making the release. Meanwhile, is there a way to document via `attributes` to indicate the reason/remedies for a breaking API change ? I searched, couldn't spot

There is a `#[deprecated(since = "5.2", note = "foo was rarely used. Users should instead use bar")]` attribute to mark a deprecated method/field. Does it meet your need? 🤔

**Comment by prataprc** [comment]
AFAIK, before hitting that deprecated warning compiler will through error on function signature-not-matching.

**Comment by drmingdrmer** [comment]
> AFAIK, before hitting that deprecated warning compiler will through error on function signature-not-matching.

I mean, mark the old method with `deprecated` and add the new method:

```rust
#[deprecated(since="", note="use populate_digests instead")]
fn populate_keys(&self) { self.populate_digests() }

fn populate_digests(&self) { /* ... */ }
```

**Comment by prataprc** [comment]
Then we will do this,

* Retain the original function signature for populate_keys()
* Use the iterator argument for populate_digests().
* Add deprecated warning for all the old APIs.

Does this sound okay ?

**Comment by drmingdrmer** [comment]
> Then we will do this,
> 
> * Retain the original function signature for populate_keys()
> * Use the iterator argument for populate_digests().

Using the iterator argument is not a breaking change. An application does not need to modify anything to upgrade xorfilter.
Thus we do not have to add a deprecation attribute in that commit b091f595599e408d8a90aa90538e04a608d25581. You can see that the test codes did not change at all in b091f595599e408d8a90aa90538e04a608d25581

> * Add deprecated warning for all the old APIs.
> 
> Does this sound okay ?

Let me update this PR to see if get it correctly:)

**Comment by prataprc** [comment]
> Using the iterator argument is not a breaking change.

Ah, you are right :) please go ahead. Cheers,

**Pull request merged**
