### PR TITLE
Add a simple CI workflow of Github action

### PR DESCRIPTION
**Pull request by uijin**
For issue #6 
When push into the repository, Github action will trigger `.github\workflows\simple-build-test.yml`, and execution result show as a badge on first line of `README.md`.

References
* [About continuous integration (Github action)](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-continuous-integration#about-continuous-integration)
* [Configuring a workflow](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow)

### CODE REVIEW

**Comment by prataprc** [comment]
Is it possible to have `build` and `test` in `--release` mode as well ? Thanks,

**Comment by uijin** [comment]
Add release build and test into `simple-build-test` workflow. 

Sometimes release tests fails as error message below:
```
running 2 tests
test tests::test_basic2 ... FAILED
test tests::test_basic1 ... FAILED

failures:

---- tests::test_basic2 stdout ----
seed 5965087604022038976
bits per entry 9.864 bits
false positive rate 0.4027%
thread 'tests::test_basic2' panicked at 'fpp(0.4027) >= 0.40', src\lib.rs:454:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by prataprc** [comment]
Requested comment from xor-filter's co-author about relaxing the false-positive threshold.

Ref: https://lemire.me/blog/2019/12/19/xor-filters-faster-and-smaller-than-bloom-filters/#comment-485921

**Comment by prataprc** [comment]
Increased the size of the test case for `basic1` and `basic2` tests. @uijin can you please rebase ?

**Comment by uijin** [comment]
Rebase complete. Fix image URL of CI badge.
@prataprc

**Pull request merged**
